#ifndef __RESTRICT_2019__
#define __RESTRICT_2019__ 1
#define _GLIBCXX_QUEUE 1
#define _GLIBCXX_STACK 1
#define _GLIBCXX_FORWARD_LIST 1
#define _GLIBCXX_LIST 1
#define _GLIBCXX_SET 1
#define _GLIBCXX_VECTOR 1
#define _GLIBCXX_MAP 1
#define _GLIBCXX_UNORDERED_SET 1
#define _GLIBCXX_UNORDERED_MAP 1
#define _GLIBCXX_ALGORITHM 1
#define _GLIBCXX_COMPLEX 1
#endif